🐛 Fix: Adjust PR link URL
knockaway/slack-rich-notify pull request #4
Opened 2020-08-26 14:39 UTC by jkulton

Looks like in the [GH Pull Request API docs](https://developer.github.com/v3/pulls/#response) `payload.url` is an API link while `payload.html_url` is the web address.

2020-08-26 15:04 UTC, thebruce approved these changes
Yay, nice fix!

2020-09-03 20:23 UTC, jsumners submitted a review, later dismissed
LGTM

2020-09-03 20:24 UTC, jsumners requested changes
Please run `npm install` so that the pre-commit hooks get added. Then use `git commit --amend --allow-empty` to force a re-commit.

2020-09-03 20:53 UTC, jsumners approved these changes

2020-09-03 20:53 UTC, merged